executable            = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/Run3_20224/CMSSW_13_0_13/src/DeepNTuples/test_2024_LT_v3/ntuple_ttbar_semilept/batchscript.sh
arguments = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/Run3_20224/CMSSW_13_0_13/src/DeepNTuples/test_2024_LT_v3/DeepNtuplizer.py inputScript=TTtoLNu2QTuneCP513p6TeVpowhegpythia8Run3Summer23BPixMiniAODv4130XmcRun32023realisticpostBPixv2v3MINIAODSIM nJobs=5 job=0 
log   = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/Run3_20224/CMSSW_13_0_13/src/DeepNTuples/test_2024_LT_v3/ntuple_ttbar_semilept/batch/con_out.0.log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/ParticleEdge/s_tagging/Tue_114154_test_2024_LT_v3/ntuple_ttbar_semilept/output/ntuple_ttbar_semilept_0.root"
use_x509userproxy = True
+MaxRuntime= 28800
RequestCpus = 2
max_transfer_output_mb = 15000
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/New_Tagger_Dev/Run3_20224/CMSSW_13_0_13/src/DeepNTuples/test_2024_LT_v3/ntuple_ttbar_semilept/batch/con_out.0.out"
max_retries = 3
queue 1
             