qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_0.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_1.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_2.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_3.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_4.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_5.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_6.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_7.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_8.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_9.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_10.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_11.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_12.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_13.sh
qsub /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/sge_14.sh
