executable            = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WminusH_HTo2B_WToLNu_M_125/batchscript.sh
arguments = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/DeepNtuplizer.py inputScript=WminusHHto2BWtoLNuM125TuneCP513p6TeVpowhegpythia8Run3Summer23BPixMiniAODv4130XmcRun32023realisticpostBPixv2v2MINIAODSIM nJobs=5 job=1 
log   = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WminusH_HTo2B_WToLNu_M_125/batch/con_out.1.log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/ParT_2024/Sun_180550_test_2024/ntuple_WminusH_HTo2B_WToLNu_M_125/output/ntuple_WminusH_HTo2B_WToLNu_M_125_1.root"
use_x509userproxy = True
+MaxRuntime= 28800
RequestCpus = 2
max_transfer_output_mb = 15000
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WminusH_HTo2B_WToLNu_M_125/batch/con_out.1.out"
max_retries = 3
queue 1
             