executable            = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_qcd_1000_1500/batchscript.sh
arguments = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/DeepNtuplizer.py inputScript=QCDHT1000to1500TuneCP5PSWeights13TeVmadgraphMLMpythia8RunIISummer19UL17MiniAODv2106Xmc2017realisticv9v1MINIAODSIM nJobs=196 job=160 
log   = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_qcd_1000_1500/batch/con_out.160.log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/PHM_tagger/Data_PHM_UL17/Sat_135511_test/ntuple_qcd_1000_1500/output/ntuple_qcd_1000_1500_160.root"
use_x509userproxy = True
+MaxRuntime= 21600
RequestCpus = 2
max_transfer_output_mb = 2000
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_qcd_1000_1500/batch/con_out.160.out"
max_retries = 3
queue 1
             