executable            = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WJetsToLNu_0J/batchscript.sh
arguments             = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/DeepNtuplizer.py inputScript=WtoLNu4JetsTuneCP513p6TeVmadgraphMLMpythia8Run3Summer23BPixMiniAODv4130XmcRun32023realisticpostBPixv2v3MINIAODSIM nJobs=5 job=$(ProcId) 
log                   = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WJetsToLNu_0J/batch/con_out.$(ProcId).log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/ParT_2024/Sun_180550_test_2024/ntuple_WJetsToLNu_0J/output/ntuple_WJetsToLNu_0J_$(ProcId).root"
use_x509userproxy = True
+MaxRuntime = 28800
max_transfer_output_mb = 15000
RequestCpus = 2
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_WJetsToLNu_0J/batch/con_out.$(ProcId).out"
max_retries = 20
queue 5
    