executable            = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batchscript.sh
arguments = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/DeepNtuplizer.py inputScript=TTToHadronicTuneCP513TeVpowhegpythia8RunIISummer20UL17MiniAOD106Xmc2017realisticv6v2MINIAODSIM nJobs=15 job=1 
log   = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/con_out.1.log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/ParticleTransformer/JustATest/Wed_112853_test_ParTEdge_small2/ntuple_ttbar_had/output/ntuple_ttbar_had_1.root"
use_x509userproxy = True
+MaxRuntime= 21600
RequestCpus = 2
max_transfer_output_mb = 15000
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/New_Tagger_Dev/CMSSW_10_6_30/src/DeepNTuples/test_ParTEdge_small2/ntuple_ttbar_had/batch/con_out.1.out"
max_retries = 3
queue 1
             