executable            = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_DYJetsToLL_1J/batchscript.sh
arguments = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/DeepNtuplizer.py inputScript=DYto2L2JetsMLL501JTuneCP513p6TeVamcatnloFXFXpythia8Run3Summer23BPixMiniAODv4130XmcRun32023realisticpostBPixv2v3MINIAODSIM nJobs=5 job=0 
log   = /afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_DYJetsToLL_1J/batch/con_out.0.log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/ParT_2024/Sun_180550_test_2024/ntuple_DYJetsToLL_1J/output/ntuple_DYJetsToLL_1J_0.root"
use_x509userproxy = True
+MaxRuntime= 28800
RequestCpus = 2
max_transfer_output_mb = 15000
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/New_Tagger_Dev/MC_ParT_2024/CMSSW_14_1_0_pre0/src/DeepNTuples/test_2024/ntuple_DYJetsToLL_1J/batch/con_out.0.out"
max_retries = 3
queue 1
             