executable            = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_bulk_grav_3/batchscript.sh
arguments             = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/DeepNtuplizer.py inputScript=BulkGravitonToHHTo4QMX600to6000MH15to250part3TuneCP513TeVmadgraphpythia8RunIISummer19UL17MiniAODv2multigridpack106Xmc2017realisticv9v1MINIAODSIM nJobs=183 job=$(ProcId) 
log                   = /afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_bulk_grav_3/batch/con_out.$(ProcId).log
getenv = True
environment = "NTUPLEOUTFILEPATH=/eos/cms/store/group/phys_btag/PHM_tagger/Data_PHM_UL17/Sat_135511_test/ntuple_bulk_grav_3/output/ntuple_bulk_grav_3_$(ProcId).root"
use_x509userproxy = True
+MaxRuntime = 21600
max_transfer_output_mb = 2000
RequestCpus = 2
transfer_output_remaps = "stdout.txt=/afs/cern.ch/work/a/ademoor/CMSSW_10_6_30/src/DeepNTuples/test/ntuple_bulk_grav_3/batch/con_out.$(ProcId).out"
max_retries = 20
queue 183
    